vim.g.mapleader = " "
vim.g.maplocalleader = " "

local options = {
	clipboard = "unnamedplus",
	completeopt = "menu,menuone,noselect",
	cursorline = true,
	expandtab = true,
	fillchars = {
	  foldopen = "",
	  foldclose = "",
	  fold = " ",
	  foldsep = " ",
	  diff = "╱",
	  eob = " ",
	},
	grepformat = "%f:%l:%c:%m",
	grepprg = "rg --vimgrep",
	ignorecase = true,
	inccommand = "nosplit",
	jumpoptions = "view",
	laststatus = 3,
	linebreak = true,
	list = true,
	mouse = "a",
	number = true,
	pumblend = 10,
	pumheight = 10,
	ruler = false,
	scrolloff = 4,
	shiftround = true,
	shiftwidth = 2,
	sidescrolloff = 8,
	signcolumn = "yes",
	smartcase = true,
	smartindent = true,
	spelllang = { "en" },
	splitbelow = true,
	splitkeep = "screen",
	splitright = true,
  statuscolumn = [[%!v:lua.require'snacks.statuscolumn'.get()]],
	tabstop = 2,
	termguicolors = true,
	timeoutlen = vim.g.vscode and 1000 or 300,
	undofile = true,
	undolevels = 10000,
	updatetime = 200,
	virtualedit = "block",
	winminwidth = 5,
	wrap = false,
	smoothscroll = true,
}

for option, value in pairs(options) do
	vim.opt[option] = value
end
